<?php

namespace App\Service;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * gwp Form Structure Service Template
 * 
 * This is based exactly on your actual GwpFormStructureService.php
 * Copy this and modify for your specific form needs.
 */
class GwpFormStructureService
{
    public function __construct(
        private ParameterBagInterface $parameterBag
    ) {}

    private function getTranslations($locale = 'en'): array
    {
        $translations = [
            'en' => [
                'full_name' => 'Full Name',
                'full_name_placeholder' => 'Full Name Here...',
                'mobile_number' => 'Mobile Number',
                'mobile_placeholder' => 'E.g. 127654321',
                'email' => 'Email',
                'email_placeholder' => 'eg. johndoe@email.com',
                'nric_passport' => 'NRIC/Passport',
                'nric_placeholder' => 'e.g. 999999-99-9999',
                'ic_no' => 'NRIC',
                'passport' => 'Passport',
                'passport_placeholder' => 'e.g. A987654321',
                'upload_receipt' => 'Upload Receipt',
                'upload_placeholder' => 'Upload Receipt Here...',
                'receipt_number' => 'Receipt Number',
                'receipt_placeholder' => 'Input Receipt Number Here...',
                'channel' => 'Channel',
                'channel_placeholder' => ' Here...',
                'recipient_full_name' => 'Recipient Full Name <span class=\'text-xs\'>(edit if required)</span>',
                'recipient_name_placeholder' => 'Recipient Full Name',
                'recipient_mobile' => 'Recipient Mobile Number <span class=\'text-xs\'>(edit if required)</span>',
                'address_1' => 'Address 1',
                'address_1_placeholder' => 'Address Line 1',
                'address_2' => 'Address 2',
                'address_2_placeholder' => 'Address Line 2',
                'postcode' => 'Postcode',
                'postcode_placeholder' => 'Postcode Here...',
                'city' => 'City',
                'city_placeholder' => 'City Here...',
                'state' => 'State',
                'state_placeholder' => 'State Here...',
                'proof_purchase' => 'All entries must be accompanied by valid proof of purchase.',
                'privacy_policy' => 'I have read and agree to the <a href=\'https://carlsbergmalaysia.com.my/privacy-policy/\' target=\'_blank\' class=\'\' style=\'color:white !important\'>privacy policy.</a>',
                'terms_conditions' => 'By participating in the contest you agree to abide by the <a href=\'https://bestwithcarlsberg.my/download/pdfs/CNY_2026_TNC.pdf?v=2\' target=\'_blank\' class=\'\' style=\'color:white !important\'>Terms & Conditions</a> of this promotion. The Organizer reserves the right to change or amend any terms relating to this Promotions.',
                #'terms_conditions' => 'By participating in the contest you agree to abide by the <a href=\'https://bestwithcarlsberg.my/download/pdfs/cny2026TNC.pdf\' target=\'_blank\' style=\'color:white !important\'>Terms & Conditions</a> of this promotion. The Organizer reserves the right to change or amend any terms relating to this Promotions.',
                'submission_form' => 'Submission Form',
                'delivery_details' => 'Delivery Details',
                'delivery_subtitle' => 'Kindly provide your delivery details so we can prepare fulfilment of your redemption once it is confirmed​.',
                'submit' => 'SUBMIT',
                'cancel' => 'CANCEL'
            ],
            'ch' => [
                'full_name' => '全名',
                'full_name_placeholder' => '请输入全名...',
                'mobile_number' => '手机号码',
                'mobile_placeholder' => '例如：127654321',
                'email' => '电子邮箱',
                'email_placeholder' => '例如：johndoe@email.com',
                'nric_passport' => '身份证/护照',
                'nric_placeholder' => '例如：999999-99-9999',
                'ic_no' => '身份证号码',
                'passport' => '护照',
                'passport_placeholder' => '例如：A987654321',
                'upload_receipt' => '上传收据',
                'upload_placeholder' => '请上传收据...',
                'receipt_number' => '收据号码',
                'receipt_placeholder' => '请输入收据号码...',
                'channel' => '渠道',
                'channel_placeholder' => '请输入...',
                'recipient_full_name' => '收件人全名 <span class=\'text-xs\'>(如需要请编辑)</span>',
                'recipient_name_placeholder' => '收件人全名',
                'recipient_mobile' => '收件人手机号码 <span class=\'text-xs\'>(如需要请编辑)</span>',
                'address_1' => '地址 1',
                'address_1_placeholder' => '地址第一行',
                'address_2' => '地址 2',
                'address_2_placeholder' => '地址第二行',
                'postcode' => '邮政编码',
                'postcode_placeholder' => '请输入邮政编码...',
                'city' => '城市',
                'city_placeholder' => '请输入城市...',
                'state' => '州属',
                'state_placeholder' => '请输入州属...',
                'proof_purchase' => '每个提交都必须附上有效的购买收据。​',
                'privacy_policy' => '我已阅读并同意<a href=\'https://carlsbergmalaysia.com.my/privacy-policy/\' target=\'_blank\' class=\'\' style=\'color:white !important\'>隐私政策</a>。',
                'terms_conditions' => '参与本次活动即表示您同意遵守本活动的<a href=\'https://bestwithcarlsberg.my/download/pdfs/CNY_2026_TNC.pdf?v=2\' target=\'_blank\' class=\'\' style=\'color:white !important\'>条款与条件</a>。主办方保留随时更改或修改本活动相关条款与条件的权利。​',
                'submission_form' => '提交表格',
                'delivery_details' => '送货详情',
                'delivery_subtitle' => '请填写您的送货详情，以便我们处理您的成功兑换。',
                'submit' => '提交',
                'cancel' => '取消'
            ]
        ];
        $proxyUrl = $this->parameterBag->get('app.proxy_url');
        if ( !str_contains($proxyUrl, "bestwithcarlsberg.my") ) {
              foreach ($translations as &$lng) {
                if (isset($lng['terms_conditions'])) {
                    $lng['terms_conditions'] = str_replace(
                        'https://bestwithcarlsberg.my/download/pdfs/',
                        '/build/pdfs/',
                        $lng['terms_conditions']
                    );
                }
            }
            unset($lng);
        } 
        return $translations[$locale] ?? $translations['en'];
    }

    public function getFormStructure($locale = 'en'): array
    {
        $t = $this->getTranslations($locale);
        
        return [
            'form_group' => [
                [
                    'index' => 0,
                    'name' => 'full_name',
                    'label' => $t['full_name'],
                    'placeholder' => $t['full_name_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 150,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'full_name'
                ],
                [
                    'index' => 1,
                    'name' => 'mobile_no',
                    'label' => $t['mobile_number'],
                    'placeholder' => $t['mobile_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 11,
                    'prefix_value' => '60',
                    'required' => true,
                    'component' => 'mobile-prefix',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '9999999999',
                    'group' => 'gwp_form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => [
                        ['label' => '+60', 'value' => '60']
                    ],
                    'alpine_model' => 'mobile_no',
                    'prefix_alpine_model' => 'mobile_prefix'
                ],
                [
                    'index' => 2,
                    'name' => 'email',
                    'label' => $t['email'],
                    'placeholder' => $t['email_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 256,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'email',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'email'
                ],
                [
                    'index' => 3,
                    'name' => 'national_id',
                    'label' => $t['nric_passport'],
                    'placeholder' => $t['nric_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => '',
                    'prefix_value' => 'NRIC',
                    'required' => true,
                    'component' => 'nricppt',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '999999-99-9999',
                    'group' => 'gwp_form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => [
                        [
                            'label' => $t['ic_no'],
                            'value' => 'NRIC',
                            'mask' => '999999-99-9999',
                            'placeholder' => $t['nric_placeholder']
                        ],
                        [
                            'label' => $t['passport'],
                            'value' => 'PASSPORT',
                            'mask' => '',
                            'placeholder' => $t['passport_placeholder']
                        ]
                    ],
                    'alpine_model' => 'national_id',
                    'prefix_alpine_model' => 'nric_prefix'
                ],
                [
                    'index' => 4,
                    'name' => 'upload_receipt',
                    'label' => $t['upload_receipt'],
                    'placeholder' => $t['upload_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => '',
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'file-upload',
                    'type' => 'file',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'helper' => false,
                    'options' => null
                ],
                [
                    'index' => 5,
                    'name' => 'receipt_no',
                    'label' => $t['receipt_number'],
                    'placeholder' => $t['receipt_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 30,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'helper' => true,
                    'options' => null,
                    'alpine_model' => 'receipt_no'
                ],
                [
                    'index' => 6,
                    'name' => 'channel_name',
                    'label' => $t['channel'],
                    'placeholder' => $t['channel_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 25,
                    'prefix_value' => '',
                    'required' => false,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => true,
                    'mask' => '',
                    'group' => 'form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'channel_name'
                ],
                [
                    'index' => 7,
                    'name' => 'form_code',
                    'label' => '',
                    'placeholder' => $t['channel_placeholder'],
                    'value' => 'SHM',
                    'custom_message' => '',
                    'maxlength' => 25,
                    'prefix_value' => '',
                    'required' => false,
                    'component' => 'hidden',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'form_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'form_code'
                ]
            ],
            'delivery_group' => [
                [
                    'index' => 0,
                    'name' => 'recipent_full_name',
                    'label' => $t['recipient_full_name'],
                    'placeholder' => $t['recipient_name_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 150,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'recipent_full_name'
                ],
                [
                    'index' => 1,
                    'name' => 'recipent_mobile_no',
                    'label' => $t['recipient_mobile'],
                    'placeholder' => $t['mobile_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 11,
                    'prefix_value' => '60',
                    'required' => true,
                    'component' => 'mobile-prefix',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '9999999999',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => [
                        ['label' => '+60', 'value' => '60']
                    ],
                    'alpine_model' => 'recipent_mobile_no',
                    'prefix_alpine_model' => 'recipent_mobile_prefix'
                ],
                [
                    'index' => 2,
                    'name' => 'address_1',
                    'label' => $t['address_1'],
                    'placeholder' => $t['address_1_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 200,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'address'
                ],
                [
                    'index' => 3,
                    'name' => 'address_2',
                    'label' => $t['address_2'],
                    'placeholder' => $t['address_2_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 200,
                    'prefix_value' => '',
                    'required' => false,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'address2'
                ],
                [
                    'index' => 4,
                    'name' => 'postcode',
                    'label' => $t['postcode'],
                    'placeholder' => $t['postcode_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 5,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'adv-select',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '99999',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'postcode'
                ],
                [
                    'index' => 5,
                    'name' => 'city',
                    'label' => $t['city'],
                    'placeholder' => $t['city_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 50,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => true,
                    'mask' => '',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'city'
                ],
                [
                    'index' => 6,
                    'name' => 'state',
                    'label' => $t['state'],
                    'placeholder' => $t['state_placeholder'],
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 50,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'input',
                    'type' => 'text',
                    'disabled' => true,
                    'mask' => '',
                    'group' => 'delivery_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null,
                    'alpine_model' => 'state'
                ]
            ],
            'checkbox_group' => [
                [
                    'index' => 0,
                    'name' => 'label',
                    'label' => $t['proof_purchase'],
                    'placeholder' => '',
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 30,
                    'prefix_value' => '',
                    'required' => false,
                    'component' => 'label',
                    'type' => 'text',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'checkbox_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null
                ],
                [
                    'index' => 1,
                    'name' => 'privacy',
                    'label' => $t['privacy_policy'],
                    'placeholder' => '',
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 30,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'checkbox',
                    'type' => 'checkbox',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'checkbox_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null
                ],
                [
                    'index' => 2,
                    'name' => 'tnc',
                    'label' => $t['terms_conditions'],
                    'placeholder' => '',
                    'value' => '',
                    'custom_message' => '',
                    'maxlength' => 30,
                    'prefix_value' => '',
                    'required' => true,
                    'component' => 'checkbox',
                    'type' => 'checkbox',
                    'disabled' => false,
                    'mask' => '',
                    'group' => 'checkbox_group',
                    'validation' => '',
                    'custom_class' => '',
                    'toggle' => false,
                    'toggleKB' => false,
                    'search' => '',
                    'search_message' => '',
                    'error_message' => '',
                    'data_url' => '',
                    'options' => null
                ]
            ]
        ];
    }
}